all: main

main: Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp
	clear && g++ -std=c++11 -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp

rmaall:
	rm main
	g++ -std=c++11 -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp

clean:
	rm main
	
