all: main

main: Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp Tree/Node.cxx Tree/Tree.cxx 
	clear && g++ -std=c++11 -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp Tree/Node.cxx Tree/Tree.cxx

rmaall:
	rm main
	g++ -std=c++11 -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp Tree/Node.cxx Tree/Tree.cxx

clean:
	rm main
	
