all: main

main: Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp Tree/Node.cxx Tree/Tree.cxx 
	g++ -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp Tree/Node.cxx Tree/Tree.cxx

rmaall:
	rm main
	g++ -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp Tree/Node.cxx Tree/Tree.cxx

clean:
	rm main
