all: main
main: Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp
	g++ -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp
allrm:
	rm main
	g++ -o main Person.cxx Package.cxx Region.cxx Office.cxx Principal.cxx main.cpp
clean:
	rm main
